if(NOT COCOA_FIX_PLUGIN OR NOT COCOA_FIX_MANIFEST)
    message(FATAL_ERROR "Specify the built Cocoa plugin and its source manifest")
endif()
file(READ "${COCOA_FIX_MANIFEST}" manifest)
string(REGEX MATCH "Deployment target: ([0-9.]+)" deployment_record "${manifest}")
set(expected_minos "${CMAKE_MATCH_1}")
if(NOT expected_minos)
    message(FATAL_ERROR "The plugin manifest has no SDK deployment target")
endif()

execute_process(COMMAND /usr/bin/otool -l "${COCOA_FIX_PLUGIN}"
    RESULT_VARIABLE inspection_status OUTPUT_VARIABLE load_commands ERROR_VARIABLE inspection_error)
if(NOT inspection_status EQUAL 0)
    message(FATAL_ERROR "Could not inspect the built plugin: ${inspection_error}")
endif()
string(REGEX MATCH "cmd LC_BUILD_VERSION\n[^\n]*\n[ \t]*platform 1\n[ \t]*minos ([0-9.]+)"
    minimum_record "${load_commands}")
set(actual_minos "${CMAKE_MATCH_1}")
if(NOT actual_minos)
    # Older Apple linkers may use the legacy macOS minimum-version command.
    string(REGEX MATCH "cmd LC_VERSION_MIN_MACOSX\n[^\n]*\n[ \t]*version ([0-9.]+)"
        minimum_record "${load_commands}")
    set(actual_minos "${CMAKE_MATCH_1}")
endif()
if(NOT actual_minos OR NOT actual_minos VERSION_EQUAL expected_minos)
    message(FATAL_ERROR "Cocoa plugin minimum macOS ${actual_minos} does not match SDK ${expected_minos}")
endif()
string(REGEX MATCHALL "cmd LC_RPATH\n[^\n]*\n[ \t]*path [^\n]*" rpaths "${load_commands}")
list(LENGTH rpaths rpath_count)
if(NOT rpath_count EQUAL 1 OR NOT rpaths MATCHES "path @loader_path/\\.\\./\\.\\./Frameworks \\(offset")
    message(FATAL_ERROR "The built Cocoa plugin must have only its bundle-relative framework rpath")
endif()
if(NOT manifest MATCHES "Verified Mach-O minimum macOS:")
    file(APPEND "${COCOA_FIX_MANIFEST}" "Verified Mach-O minimum macOS: ${actual_minos}\n")
endif()
message(STATUS "Verified Cocoa Mach-O minimum macOS ${actual_minos} and bundle-relative rpath")
